package com.routechain.v2.decision;

enum ComparisonLens {
    OBSERVATION_NORMALIZATION_LENS,
    PAIR_SUPPORT_LENS,
    ANCHOR_STABILITY_LENS,
    DRIVER_FIT_LENS,
    ROUTE_FEASIBILITY_LENS,
    ROUTE_DOMINANCE_LENS,
    SCENARIO_ROBUSTNESS_LENS,
    GLOBAL_SELECTION_LENS,
    EXECUTION_SAFETY_LENS
}
