package com.routechain.v2.decision;

enum GeospatialLens {
    WORLD_STATE_LENS,
    BUNDLE_GEOMETRY_LENS,
    ANCHOR_AREA_LENS,
    DRIVER_CORRIDOR_ENTRY_LENS,
    ROUTE_CORRIDOR_LENS,
    ROUTE_DOMINANCE_GEO_LENS,
    SCENARIO_OVERLAY_LENS,
    FINAL_CONFLICT_GEO_LENS,
    EXECUTION_VALIDATION_LENS
}
