package com.routechain.v2;

import com.routechain.config.RouteChainDispatchV2Properties;
import com.routechain.v2.feedback.FeedbackStorageMode;
import org.junit.jupiter.api.Test;

import java.time.Duration;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class RouteChainDispatchV2PropertiesTest {

    @Test
    void exposesBootstrapDefaults() {
        RouteChainDispatchV2Properties properties = RouteChainDispatchV2Properties.defaults();
        assertEquals(Duration.ofSeconds(30), properties.getTick());
        assertEquals(Duration.ofSeconds(45), properties.getBuffer().getHoldWindow());
        assertEquals(24, properties.getCluster().getMaxSize());
        assertEquals(5, properties.getBundle().getMaxSize());
        assertEquals(12, properties.getBundle().getTopNeighbors());
        assertEquals(16, properties.getBundle().getBeamWidth());
        assertEquals(3, properties.getCandidate().getMaxAnchors());
        assertEquals(8, properties.getCandidate().getMaxDrivers());
        assertEquals(4, properties.getCandidate().getMaxRouteAlternatives());
        assertEquals(22.0, properties.getContext().getBaselineSpeedKph());
        assertEquals(1.28, properties.getContext().getHeavyRainMultiplier());
        assertEquals(1.07, properties.getContext().getLightRainMultiplier());
        assertEquals(8, properties.getContext().getTomtomRefineBudgetPerTick());
        assertEquals(Duration.ofMinutes(15), properties.getContext().getFreshness().getWeatherMaxAge());
        assertEquals(Duration.ofMinutes(10), properties.getContext().getFreshness().getTrafficMaxAge());
        assertEquals(Duration.ofMinutes(30), properties.getContext().getFreshness().getForecastMaxAge());
        assertEquals(Duration.ofMillis(150), properties.getContext().getTimeouts().getEtaMlTimeout());
        assertEquals(2.2, properties.getPair().getPickupDistanceKmThreshold());
        assertEquals(15, properties.getPair().getReadyGapMinutesThreshold());
        assertEquals(55.0, properties.getPair().getDropAngleDiffDegreesThreshold());
        assertEquals(1.25, properties.getPair().getMergeEtaRatioThreshold());
        assertEquals(0.45, properties.getPair().getScoreThreshold());
        assertEquals(Duration.ofMillis(120), properties.getPair().getMlTimeout());
        assertEquals(12, properties.getPair().getMaxCandidateNeighborsPerOrder());
        assertEquals(1.4, properties.getPair().getWeatherTightened().getPickupDistanceKmThreshold());
        assertEquals(10, properties.getPair().getWeatherTightened().getReadyGapMinutesThreshold());
        assertEquals(1.15, properties.getPair().getWeatherTightened().getMergeEtaRatioThreshold());
        assertEquals(15, properties.getMicroCluster().getTimeBucketMinutes());
        assertEquals(0.55, properties.getMicroCluster().getSplitScoreThreshold());
        assertEquals(0.52, properties.getBoundaryExpansion().getMinSupportScoreThreshold());
        assertEquals(2, properties.getBoundaryExpansion().getMaxBoundaryOrdersPerCluster());
        assertEquals(0.62, properties.getBoundaryExpansion().getWeatherTightenedSupportThreshold());
        assertEquals(1.18, properties.getScenario().getWeatherBadEtaMultiplier());
        assertEquals(1.22, properties.getScenario().getTrafficBadEtaMultiplier());
        assertEquals(6, properties.getScenario().getMerchantDelayMinutes());
        assertEquals(0.08, properties.getScenario().getDriverDriftPenalty());
        assertEquals(0.06, properties.getScenario().getPickupQueuePenalty());
        assertEquals(0.58, properties.getScenario().getForecast().getZoneBurstThreshold());
        assertEquals(0.57, properties.getScenario().getForecast().getDemandShiftThreshold());
        assertEquals(0.55, properties.getScenario().getForecast().getPostDropShiftThreshold());
        assertEquals(0.55, properties.getScenario().getForecast().getConfidenceThreshold());
        assertFalse(properties.isEnabled());
        assertFalse(properties.isMlEnabled());
        assertFalse(properties.isSidecarRequired());
        assertFalse(properties.isSelectorOrtoolsEnabled());
        assertTrue(properties.isWarmStartEnabled());
        assertTrue(properties.isHotStartEnabled());
        assertFalse(properties.isTomtomEnabled());
        assertTrue(properties.isOpenMeteoEnabled());
        assertFalse(properties.getWeather().isEnabled());
        assertEquals("http://127.0.0.1:8094", properties.getWeather().getBaseUrl());
        assertEquals(Duration.ofMillis(75), properties.getWeather().getConnectTimeout());
        assertEquals(Duration.ofMillis(180), properties.getWeather().getReadTimeout());
        assertEquals(0.45, properties.getWeather().getConfidenceThreshold());
        assertTrue(properties.getWeather().isStaleSignalSuppressionEnabled());
        assertFalse(properties.getTraffic().isEnabled());
        assertEquals("http://127.0.0.1:8095", properties.getTraffic().getBaseUrl());
        assertEquals(Duration.ofMillis(75), properties.getTraffic().getConnectTimeout());
        assertEquals(Duration.ofMillis(180), properties.getTraffic().getReadTimeout());
        assertEquals(0.5, properties.getTraffic().getConfidenceThreshold());
        assertEquals(8, properties.getTraffic().getRefineBudgetPerTick());
        assertEquals(1, properties.getTraffic().getMaxRefinedLegsPerRequest());
        assertFalse(properties.getMl().getForecast().isEnabled());
        assertEquals("http://127.0.0.1:8096", properties.getMl().getForecast().getBaseUrl());
        assertEquals(Duration.ofMillis(75), properties.getMl().getForecast().getConnectTimeout());
        assertEquals(Duration.ofMillis(180), properties.getMl().getForecast().getReadTimeout());
        assertTrue(properties.getFeedback().isDecisionLogEnabled());
        assertTrue(properties.getFeedback().isSnapshotEnabled());
        assertTrue(properties.getFeedback().isReplayEnabled());
        assertEquals(FeedbackStorageMode.IN_MEMORY, properties.getFeedback().getStorageMode());
        assertEquals("build/dispatch-v2-feedback", properties.getFeedback().getBaseDir());
        assertEquals(20, properties.getFeedback().getRetention().getMaxFiles());
        assertTrue(properties.getWarmHotStart().isLoadLatestSnapshotOnBoot());
        assertTrue(properties.getPerformance().isTelemetryEnabled());
        assertFalse(properties.getPerformance().isBudgetEnforcementEnabled());
        assertEquals(Duration.ofMillis(1200), properties.getPerformance().getTotalDispatchBudget());
        assertEquals(Duration.ofMillis(300), properties.getPerformance().getStageBudgets().get("eta/context"));
        assertEquals(Duration.ofMillis(15), properties.getPerformance().getStageBudgets().get("order-buffer"));
        assertEquals(Duration.ofMillis(180), properties.getPerformance().getStageBudgets().get("pair-graph"));
        assertEquals(Duration.ofMillis(25), properties.getPerformance().getStageBudgets().get("micro-cluster"));
        assertEquals(Duration.ofMillis(40), properties.getPerformance().getStageBudgets().get("boundary-expansion"));
        assertEquals(Duration.ofMillis(240), properties.getPerformance().getStageBudgets().get("bundle-pool"));
        assertEquals(Duration.ofMillis(20), properties.getPerformance().getStageBudgets().get("pickup-anchor"));
        assertEquals(Duration.ofMillis(180), properties.getPerformance().getStageBudgets().get("driver-shortlist/rerank"));
        assertEquals(Duration.ofMillis(320), properties.getPerformance().getStageBudgets().get("route-proposal-pool"));
        assertEquals(Duration.ofMillis(220), properties.getPerformance().getStageBudgets().get("scenario-evaluation"));
        assertEquals(Duration.ofMillis(180), properties.getPerformance().getStageBudgets().get("global-selector"));
        assertEquals(Duration.ofMillis(40), properties.getPerformance().getStageBudgets().get("dispatch-executor"));
        assertEquals("llm", properties.getDecision().getMode());
        assertTrue(properties.getDecision().isFallbackToLegacy());
        assertEquals("9router", properties.getDecision().getLlm().getProvider());
        assertEquals("http://127.0.0.1:20128/v1", properties.getDecision().getLlm().getBaseUrl());
        assertEquals("responses", properties.getDecision().getLlm().getWireApi());
        assertEquals("cx/gpt-5.5", properties.getDecision().getLlm().getModel());
        assertEquals("OPENAI_API_KEY", properties.getDecision().getLlm().getApiKeyEnv());
        assertEquals(Duration.ofSeconds(45), properties.getDecision().getLlm().getTimeoutMs());
        assertEquals(2, properties.getDecision().getLlm().getMaxRetries());
        assertFalse(properties.getDecision().getLlm().isParallelToolCalls());
        assertTrue(properties.getDecision().getLlm().isStrictStructuredOutputs());
    }
}
