import { useMemo } from 'react';
import type { LiveMapModel, LiveMapPoint } from './liveMapModel';

export function LiveSyntheticMap({ model, showMlImpact }: { model: LiveMapModel; showMlImpact: boolean }) {
  const points = [...model.drivers, ...model.pickups, ...model.dropoffs];
  const project = useProjector(points);
  return <svg className="live-synthetic-map" viewBox="0 0 900 520" role="img" aria-label="Synthetic live dispatch map" data-testid="live-synthetic-map"><defs><pattern id="live-grid" width="42" height="42" patternUnits="userSpaceOnUse"><path d="M42 0 L0 0 0 42" fill="none" stroke="rgba(148,163,184,.12)" /></pattern><filter id="live-glow"><feGaussianBlur stdDeviation="4" result="blur" /><feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge></filter></defs><rect width="900" height="520" rx="28" fill="url(#live-grid)" />{model.previousRoutes.map((route) => <path key={route.id} d={routePath(route.points, project)} fill="none" stroke="#64748b" strokeWidth="5" strokeDasharray="10 10" opacity=".55" strokeLinecap="round" strokeLinejoin="round" />)}{model.routes.map((route) => <path key={route.id} d={routePath(route.points, project)} fill="none" stroke={route.mlTouched && showMlImpact ? '#a855f7' : routeColor(route.driverId)} strokeWidth={route.mlTouched && showMlImpact ? 8 : 5} opacity=".9" strokeLinecap="round" strokeLinejoin="round" />)}{points.map((point) => { const pos = project(point); return <g key={point.id} className={`live-map-pin ${point.kind.toLowerCase()} ${point.frozen ? 'frozen' : ''} ${point.mlTouched && showMlImpact ? 'ml-touched' : ''}`} transform={`translate(${pos.x} ${pos.y})`}><circle r={point.kind === 'DRIVER' ? 17 : point.risk === 'HIGH' ? 15 : 12} fill={fill(point)} opacity=".20" filter="url(#live-glow)" /><circle r={point.kind === 'DRIVER' ? 11 : 9} fill="#020617" stroke={border(point, showMlImpact)} strokeWidth={point.frozen ? 5 : point.mlTouched && showMlImpact ? 4 : 3} /><text y="4" textAnchor="middle" fontSize="9" fontWeight="800" fill="#e5f5ff">{point.kind === 'DRIVER' ? point.label : point.kind[0]}</text><title>{point.label} · risk ${point.risk ?? 'LOW'} · frozen ${point.frozen ? 'true' : 'false'} · selected by GreedRL + Tabular</title></g>; })}</svg>;
}

function routePath(points: LiveMapPoint[], project: (point: LiveMapPoint) => { x: number; y: number }) { return points.map((point, index) => `${index === 0 ? 'M' : 'L'} ${project(point).x} ${project(point).y}`).join(' '); }
function useProjector(points: LiveMapPoint[]) { return useMemo(() => { const safe = points.length ? points : [{ lat: 10.75, lng: 106.7 } as LiveMapPoint]; const latMin = Math.min(...safe.map((point) => point.lat)); const latMax = Math.max(...safe.map((point) => point.lat)); const lngMin = Math.min(...safe.map((point) => point.lng)); const lngMax = Math.max(...safe.map((point) => point.lng)); const latSpan = Math.max(0.001, latMax - latMin); const lngSpan = Math.max(0.001, lngMax - lngMin); return (point: LiveMapPoint) => ({ x: 70 + ((point.lng - lngMin) / lngSpan) * 760, y: 450 - ((point.lat - latMin) / latSpan) * 380 }); }, [points]); }
function fill(point: LiveMapPoint) { if (point.kind === 'DRIVER') return '#22d3ee'; if (point.kind === 'PICKUP') return '#3b82f6'; return '#22c55e'; }
function border(point: LiveMapPoint, showMlImpact: boolean) { if (point.frozen) return '#94a3b8'; if (showMlImpact && point.mlTouched) return '#d8b4fe'; if (point.risk === 'HIGH') return '#fb7185'; return '#e5f5ff'; }
function routeColor(driverId: string) { return driverId.endsWith('2') ? '#34d399' : '#22d3ee'; }

