package com.routechain.v2.hybrid;

public enum CandidateSource {
    IRX_NATIVE,
    IRX_ML_FUSED,
    SINGLETON,
    DISTANCE_SEED,
    CLARKE_WRIGHT,
    SWEEP,
    REGRET_K,
    ORTOOLS_SEED,
    PYVRP_SEED,
    VROOM_SEED,
    VROOM_SEED_IMPROVED,
    PYVRP_SEED_IMPROVED,
    ORTOOLS_SEED_IMPROVED,
    BEST_EXTERNAL_SEED_IMPROVED,
    IRX_NATIVE_IMPROVED,
    ROUTEFINDER_ML
}
