param([string]$BaseUrl="http://localhost:18116",[Alias("OutputDir")][string]$OutDir="artifacts/test-reports/v0.9.11-dynamic-ml-dispatch/dynamic-stress",[switch]$SkipCompile)
$ErrorActionPreference="Stop";$root=(Resolve-Path (Join-Path $PSScriptRoot "..")).Path;$out=Join-Path $root $OutDir;New-Item -ItemType Directory -Force -Path $out|Out-Null
$headers=@{"X-Api-Key"="demo-key";"X-Tenant-Id"="demo"};$apiErrors=0
function Post($u,$b){try{Invoke-RestMethod -Method Post -Uri $u -Headers $headers -ContentType "application/json" -Body ($b|ConvertTo-Json -Depth 30) -TimeoutSec 120}catch{$script:apiErrors++;throw}}
function Get($u){try{Invoke-RestMethod -Method Get -Uri $u -Headers $headers -TimeoutSec 120}catch{$script:apiErrors++;throw}}
if(-not $SkipCompile){Push-Location $root;try{.\gradlew.bat compileJava --no-daemon --console=plain *> (Join-Path $out "compileJava.log")}finally{Pop-Location}}
$job=Post "$BaseUrl/api/v1/live/jobs" @{jobId="dynamic-stress";tenantId="demo"};$cycles=@();$ordersInjected=0;$telemetry=0
for($c=1;$c -le 20;$c++){for($j=1;$j -le 3 -and $ordersInjected -lt 50;$j++){$ordersInjected++;Post "$BaseUrl/api/v1/live/jobs/$($job.jobId)/orders" @{orders=@(@{orderId="STRESS-ORD-$ordersInjected";pickup=@{lat=10.7+$ordersInjected/10000;lng=106.6};dropoff=@{lat=10.8;lng=106.7+$ordersInjected/10000};deadline="2026-05-20T10:30:00Z";load=1;priority=if($ordersInjected%7 -eq 0){"HIGH"}else{"NORMAL"}})}|Out-Null};$driver="D0"+(($c%5)+1);Post "$BaseUrl/api/v1/live/jobs/$($job.jobId)/drivers/$driver/telemetry" @{driverId=$driver;lat=10.72+$c/10000;lng=106.62;status=if($c%6 -eq 0){"DELAYED"}else{"EN_ROUTE"};currentStopId=if($c -gt 1){"PICKUP:STRESS-ORD-1"}else{$null}}|Out-Null;$telemetry++;$cycles+=Post "$BaseUrl/api/v1/live/jobs/$($job.jobId)/cycle" @{returnDiagnostics=$true};if($c%10 -eq 0){$cycles+=Post "$BaseUrl/api/v1/live/jobs/$($job.jobId)/rescue" @{}}}
$state=Get "$BaseUrl/api/v1/live/jobs/$($job.jobId)/state";$orderIds=@($state.orders|%{$_.order.orderId});$dup=($orderIds|Group-Object|? Count -gt 1).Count;$missing=if([int]$state.assigned+[int]$state.buffered -lt $ordersInjected){1}else{0}
$s=[pscustomobject]@{version="v0.9.11-dynamic-ml-dispatch";gate="dynamic-stress";generatedAt=(Get-Date).ToUniversalTime().ToString("o");compileJava=if($SkipCompile){"SKIPPED"}else{"PASS"};cyclesCompleted=$cycles.Count;ordersInjected=$ordersInjected;driverTelemetryUpdates=$telemetry;forecastOutputUsed=@($cycles|? forecastUsed).Count;greedRlActionUsed=@($cycles|?{$_.greedRlAction -ne "KEEP"}).Count;triModelRepairUsed=@($cycles|? triModelRepairUsed).Count;apiErrors=$apiErrors;duplicateAssignmentViolations=$dup;missingOrderViolations=$missing;staleBufferedOrders=[int]$state.buffered;frozenStopViolations=(@($cycles|%{[int]$_.diagnostics.frozenStopViolations})|Measure-Object -Sum).Sum;pickupDropoffViolations=(@($cycles|%{[int]$_.diagnostics.pickupDropoffViolations})|Measure-Object -Sum).Sum;capacityViolations=(@($cycles|%{[int]$_.diagnostics.capacityViolations})|Measure-Object -Sum).Sum;overallPass=$false}
$s.overallPass=$s.cyclesCompleted -ge 20 -and $s.ordersInjected -ge 50 -and $s.apiErrors -eq 0 -and $s.duplicateAssignmentViolations -eq 0 -and $s.missingOrderViolations -eq 0 -and $s.staleBufferedOrders -eq 0 -and $s.frozenStopViolations -eq 0 -and $s.pickupDropoffViolations -eq 0 -and $s.capacityViolations -eq 0
$s|ConvertTo-Json -Depth 100|Set-Content -Encoding UTF8 (Join-Path $out "dynamic-stress-summary.json");$state|ConvertTo-Json -Depth 100|Set-Content -Encoding UTF8 (Join-Path $out "dynamic-stress-state.json");if(-not $s.overallPass){throw "dynamic stress FAIL"};Write-Host "[DYNAMIC-STRESS] PASS"
