package com.routechain.v2.bundle;

public enum BundleFamily {
    COMPACT_CLIQUE,
    CORRIDOR_CHAIN,
    FAN_OUT_LIGHT,
    BOUNDARY_CROSS,
    URGENT_COMPANION,
    LANDING_VALUE_BUNDLE,
    SAME_RESTAURANT,
    SAME_FOOD_COURT,
    SAME_DELIVERY_ZONE,
    CORRIDOR,
    NEIGHBORHOOD,
    ACTIVE_ROUTE_ADDON,
    LATE_RISK_RESCUE,
    HOLD_TO_BATCH,
    SINGLETON_FALLBACK,
    URGENT_SINGLE_FALLBACK,
    DIVERSITY_EXPLORATION
}
